AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM private data vault template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  VaultTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: pk
        Type: String
      # Not setting ProvisionedThroughput as this is a test and we do not expect load. 
      # This could be different in a real world scenario.
  VaultFunction:
    Type: AWS::Serverless::Function
    Connectors:
      MyTableConn:
        Properties:
          Destination:
            Id: VaultTable
          Permissions:
            - Read
            - Write
    Properties:
      CodeUri: data_vault/
      Handler: owner.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          # This is the DynamoDB table name
          TABLE_NAME:
            Ref: VaultTable
      Architectures:
      - x86_64
      Events:
        DataStore:
          Type: Api
          Properties:
            Path: /
            Method: post
        DataRemove:
          Type: Api
          Properties:
            Path: /
            Method: patch
